version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crud-react
    environment:
      - API_URL=http://localhost:9000
      - BACKEND_FRAMEWORK=Express.js
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app/dist